### ISSUE TITLE
构建出错

### ISSUE THREAD

**Issue by stgzhangzheyi** [sibaiabis/veet#1]
下载后打包。
生产环境下用的是win.load('app:// ./html')
![image](https://user-images.githubusercontent.com/44356902/128962288-e139174a-d36f-415b-b0c8-713484ab32ed.png)
难道是我哪里错了呢？
结果不对
接着我换了一种方式：
![image](https://user-images.githubusercontent.com/44356902/128962153-0574c54f-e112-42ca-adf9-e4a9ae0ae5b5.png)
 // let wincc = `file://${__dirname}/index.html`
    // win.loadURL(wincc)
我不知道为什么静态资源加载不了，app://注释了，为什么还存在。
希望您能帮我解答，不胜感激

**Comment by sibaiabis** [comment]
生产环境下用的是win.load('app:// ./html')  这个地方不对吧？哪有./html呀

**Comment by sibaiabis** [comment]
> 下载后打包。
> 生产环境下用的是win.load('app:// ./html')
> ![image](https://user-images.githubusercontent.com/44356902/128962288-e139174a-d36f-415b-b0c8-713484ab32ed.png)
> 难道是我哪里错了呢？
> 结果不对
> 接着我换了一种方式：
> ![image](https://user-images.githubusercontent.com/44356902/128962153-0574c54f-e112-42ca-adf9-e4a9ae0ae5b5.png)
> // let wincc = `file://${__dirname}/index.html`
> // win.loadURL(wincc)
> 我不知道为什么静态资源加载不了，app://注释了，为什么还存在。
> 希望您能帮我解答，不胜感激

**Comment by sibaiabis** [comment]
再有问题可wx：sibaiabis找我

**Comment by stgzhangzheyi** [comment]
就是我遇到一个问题啊： 写一个登录框。 当我没登录之前，先将主窗口隐藏，打开登录窗。等登录成功后，关闭登录窗，接着将登录信息token用localstorege保存起来。但是我在background.js怎么能够拿到这些信息啊？因为我需要用这些信息判断我是否登录，从而将登录框隐藏，显示主窗口。
