### ISSUE TITLE
login

### ISSUE THREAD

**Issue by stgzhangzheyi** [sibaiabis/veet#2]
就是我遇到一个问题啊： 写一个登录框。 当我没登录之前，先监听token,将主窗口隐藏，打开登录窗。等登录成功后，关闭登录窗，接着将登录信息token用localstorege保存起来。但是我在background.js怎么能够拿到这些信息啊？因为我需要用这些信息判断我是否登录，从而将登录框隐藏，显示主窗口。

**Comment by sibaiabis** [comment]
主进程访问渲染进程？？？

**Comment by stgzhangzheyi** [comment]
![image](https://user-images.githubusercontent.com/44356902/129159824-53269004-bfb0-41b9-a115-4c912b675caa.png)
就是登录和主页的设计思维。
我不想用路由跳转的方式，而是直接用一个登录窗和主窗的方式实现，但我不知道怎么能够监听登录token.

**Comment by stgzhangzheyi** [comment]
![image](https://user-images.githubusercontent.com/44356902/129160064-c24c8199-5f09-4af9-9e37-8c24ef489ad8.png)

**Comment by sibaiabis** [comment]
emm这个我也不知道咋搞呢，我就是个业余的hhh
你可以问问你们公司大佬呐 -_-
（ps：这个问题我也想知道咋解决）

**Comment by sibaiabis** [comment]
看看这些搜索呢：https://cn.bing.com/search?q=electron%E7%9B%91%E5%90%AC%E4%B8%BB%E7%AA%97%E5%8F%A3

**Comment by stgzhangzheyi** [comment]
> 看看这些搜索呢：https://cn.bing.com/search?q=electron%E7%9B%91%E5%90%AC%E4%B8%BB%E7%AA%97%E5%8F%A3

ok,感谢您的回答，这些并不能帮助我，最好要一个demo。如有好的方案的例子，请及时提供给我，不胜感激。

**Comment by stgzhangzheyi** [comment]
> emm这个我也不知道咋搞呢，我就是个业余的hhh
> 你可以问问你们公司大佬呐 -_-
> （ps：这个问题我也想知道咋解决）

我正在寻求一份高薪工作，请问您招人吗？

**Comment by sibaiabis** [comment]
> > emm这个我也不知道咋搞呢，我就是个业余的hhh
> > 你可以问问你们公司大佬呐 -_-
> > （ps：这个问题我也想知道咋解决）
> 
> 我正在寻求一份高薪工作，请问您招人吗？

先投简历过来

**Comment by stgzhangzheyi** [comment]
> > > emm这个我也不知道咋搞呢，我就是个业余的hhh
> > > 你可以问问你们公司大佬呐 -_-
> > > （ps：这个问题我也想知道咋解决）
> > 
> > 
> > 我正在寻求一份高薪工作，请问您招人吗？
> 
> 先投简历过来

公司地址？？

**Comment by sibaiabis** [comment]
> > > > emm这个我也不知道咋搞呢，我就是个业余的hhh
> > > > 你可以问问你们公司大佬呐 -_-
> > > > （ps：这个问题我也想知道咋解决）
> > > 
> > > 
> > > 我正在寻求一份高薪工作，请问您招人吗？
> > 
> > 
> > 先投简历过来
> 
> 公司地址？？

私
